<?php
/**
 * @file
 * Provides formats.
 */

/**
 * Implements hook_date_format_types().
 */
function nas_formats_date_format_types() {
  return array(
    'nas_date' => t('NAS Date'),
  );
}

/**
 * Implements hook_date_formats().
 */
function nas_formats_date_formats() {
  $formats = array(
    array(
      'type' => 'nas_date',
      'format' => 'F j, Y',
      'locales' => array(),
    ),
  );
  return $formats;
}
