---
# This playbook should be executed using reinstall.sh script
# Developed for ansible version >= 1.7
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    drupal_user: admin
    drupal_pass: propeople
    installation_profile_name: pp
    mysql_user: drupal
    mysql_pass: drupal
    mysql_db: drupal
    cache_folder: /var/www/cache
    php_env_vars: 'APP_ENV=dev' # APP_ENV=dev - this varible will be set at PR_BUILDER from CI shell executor.
    site_url: 'http://nas.192.168.56.132.xip.io/'

  tasks:

  - name: Droping drupal database
    mysql_db: name={{ mysql_db }} state=absent

  - name: Creating drupal database
    mysql_db: name={{ mysql_db }} state=present
    
  - name: Creating cache folder
    sudo: yes
    file: path={{ cache_folder }} state=directory recurse=yes

  - name: Installing drupal
    sudo: yes
    shell: "{{ php_env_vars}} drush -y si {{ installation_profile_name }} --db-url=mysql://{{ mysql_user }}:{{ mysql_pass }}@127.0.0.1:/{{ mysql_db }} --account-name={{ drupal_user }} --account-pass={{ drupal_pass }} --uri={{ site_url }} base_url={{ site_url }}"

  - name: Solr - clearing index
    sudo: yes
    shell: "{{ php_env_vars}} drush -y search-api-clear -l {{ site_url }}"

  - name: Solr - reindexing
    sudo: yes
    shell: "{{ php_env_vars}} drush -y search-api-index -l {{ site_url }}"

  handlers:
#    - name: import livedb
#      mysql_db: name=livedrupal state=import target=livedb.sql.gz
#      ignore_errors: yes
