---
# This playbook should be executed using ansible-playbook command
# Developed for ansible version >= 1.7
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    # this variable will be overridden from jenkins.
    workspace_root: .
    artifacts_file: commentinfo.md
    webroot: http://localhost
    installation_profile_name: pp
    phpcs_extensions: php,inc,install,module
    custom_modules_path: sites/all/modules/custom/
    custom_themes_path: sites/all/themes/custom
    ignore_path: sites/all/themes/circle

    phpcs_standards:
      - Drupal
      - DrupalPractice
      - DrupalSecure

    jshint_folders:
      - { name: 'modules', path: 'sites/all/modules/custom' }
      - { name: 'themes', path: 'sites/all/themes/custom' }
      - { name: 'profile', path: 'profiles/pp' }

    scsslint_folders:
      - { name: 'themes', path: 'sites/all/themes/custom' }

  pre_tasks:

  - name: PHP CodeSniffer
    sudo: yes
    shell: 'echo "CodeSniffer: {{ item }} standard file {{ webroot }}/{{ item }}sniff.txt" >> {{ workspace_root }}/{{ artifacts_file }} && phpcs --standard={{ item }} --extensions={{ phpcs_extensions }} -n {{ custom_modules_path }} profiles/{{ installation_profile_name }} {{ custom_themes_path }} --report-file={{ item }}sniff.txt --ignore={{ ignore_path }}'
    with_items: phpcs_standards

  - name: JSHint
    sudo: yes
    shell: 'echo "JSHint: {{ item.name }} standard file {{ webroot }}/{{ item.name }}jshint.txt" >> {{ workspace_root }}/{{ artifacts_file }} && find {{ item.path }} -type f \( -iname "*.js" ! -iname "*.min.js" \) -print0 | sudo xargs -0 jshint > {{ item.name }}jshint.txt'
    with_items: "jshint_folders"

  - name: SCSS lint
    sudo: yes
    ignore_errors: yes
    shell: 'echo "SCSS-lint: {{ item.name }} standard file {{ webroot }}/scsslint{{ item.name }}.txt" >> {{ workspace_root }}/{{ artifacts_file }} && find {{ item.path }} -name "*.scss" -print0 | xargs -0 scss-lint > scsslint{{ item.name }}.txt || true'
    with_items: scsslint_folders

  - name: Website credentials
    lineinfile: dest={{ workspace_root }}/{{ artifacts_file }} line="Build site installed at {{ webroot }}"