<?php

/**
 * @file
 * define ctools content type.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function nas_footer_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme().
 */
function nas_footer_theme() {
  return array(
      'nas_footer_menu' => array(
          'arguments' => array('menu_tree' => NULL),
          'template' => 'templates/nas-footer-menu',
      ),
      'nas_footer_copyright_menu' => array(
          'arguments' => array('menu_tree' => NULL),
          'template' => 'templates/nas-footer-copyright-menu',
      ),
      'nas_footer' => array(
          'arguments' => array(
              'logo' => NULL,
              'mission_title' => NULL,
              'mission' => NULL,
              'copyright' => NULL,
              'footer_menu' => NULL,
              'footer_copyright_menu' => NULL,
          ),
          'template' => 'templates/nas-footer',
      ),
      'nas_stay_abreast' => array(
          'arguments' => array(
              'headline' => NULL,
              'caption' => NULL,
              'form' => NULL,
          ),
          'template' => 'templates/nas-stay-abreast'
      )
  );
}

function nas_footer_mail_subscription_form($form, &$form_state) {
  $form['email'] = array(
      '#type' => 'textfield',
      '#attributes' => array(
          'placeholder' => array(t('Enter your email address')),
          'class' => array('mailing-list-input', 'radius')
      ),
      '#nowrap' => TRUE,
      '#size' => ''
  );
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Sign Up'),
      '#attributes' => array(
          'class' => array('button', 'tomato', 'large')
      ),
      '#nowrap' => TRUE
  );
  $form['#attributes']['class'] = array('mailing-list-form');

  return $form;
}