<?php

/**
 * @file
 * Customizations of the menu.
 */

define('NAS_MENU_MAIN_NAVIGATION', 'menu-header-big-main-menu');

/**
 * Implements hook_menu_attribute_info().
 */
function nas_menu_menu_attribute_info_alter(array &$attributes) {
  // Add a Tabindex attribute.
  $attributes['liclass'] = array(
    'label' => t('List item class'),
    'description' => t('Specifies class of LI element.'),
  );

  // Remove the Access Key attribute.
  foreach (array('accesskey', 'title', 'id', 'name', 'rel', 'style', 'target') as $key) {
    unset($attributes[$key]);
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function nas_menu_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme().
 */
function nas_menu_theme() {
  return array(
    'nas_small_header' => array(
      'arguments' => array('menu_tree' => NULL),
      'template' => 'templates/nas-small-header',
    ),
    'nas_don_t_miss' => array(
      'arguments' => array('items' => NULL, 'contextual_links' => NULL),
      'template' => 'templates/nas-don-t-miss',
    ),
    'nas_big_header' => array(
      'arguments' => array(
        'items' => NULL,
        'frontpage_link' => NULL,
        'form' => NULL,
      ),
      'template' => 'templates/nas-big-header',
    ),
    'nas_guide_bar' => array(
      'arguments' => array(
        'div_attributes' => NULL,
        'title' => NULL,
        'preamble' => NULL,
        'logo' => NULL,
        'contextual_links' => NULL,
      ),
      'template' => 'templates/nas-guide-bar',
    ),
    'nas_guide_bar_search' => array(
      'arguments' => array(
        'div_attributes' => NULL,
        'title' => NULL,
        'preamble' => NULL,
        'logo' => NULL,
        'exposed_form' => NULL,
        'contextual_links' => NULL,
      ),
      'template' => 'templates/nas-guide-bar-search',
    ),
  );
}


function nas_menu_search_form($form, &$form_state) {
  $form['search'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => array(t('Search the Audubon network')),
      'class' => array('header-search-input', 'radius')
    ),
    '#size' => '',
    '#id' => 'nas-menu-search-input'
  );
  $form['nas_search_btn'] = array(
    '#type' => 'button',
    '#value' => '<i class="icon-magnifier"></i>',
    '#attributes' => array(
      'class' => array('header-search-button', 'button', 'large', 'pea-green')
    ),
  );
  $search_close = l('<i class="icon-close"></i>', '<front>', array(
    'html' => TRUE,
    'attributes' => array(
      'class' => array('hide-for-tiny', 'hide-for-small', 'hide-for-medium', 'header-search-close')
    )
      )
  );
  $form['search_close'] = array(
    '#markup' => $search_close
  );

  return $form;
}

/**
 * Render contextual links for menu
 */
function nas_menu_cl($menu_delta, $additional_links = array()) {
  if (!module_exists('contextual') || !user_access('access contextual links')) {
    return FALSE;
  }
  $contextual_links['#contextual_links']['menu'] = array('admin/structure/menu/manage', array($menu_delta));
  $contextual_links = contextual_pre_render_links($contextual_links);
  if (isset($contextual_links['#links']['menu-edit'])) {
    unset($contextual_links['#links']['menu-edit']);
  }
  if (isset($contextual_links['#links']['menu-list'])) {
    $contextual_links['#links']['menu-list']['title'] = t('edit links');
  }
  $build = array(
    '#prefix' => '<div class="contextual-links-wrapper">',
    '#suffix' => '</div>',
    '#theme' => 'links__contextual',
    '#links' => array_merge($contextual_links['#links'], $additional_links),
    '#attributes' => array('class' => array('contextual-links')),
    '#attached' => array(
      'library' => array(array('contextual', 'contextual-links')),
    ),
  );

  return drupal_render($build);
}

/**
 * Preprocess function for nas-guide-bar-search.tpl.php.
 */
function nas_menu_preprocess_nas_guide_bar_search(&$variables) {
  drupal_add_js(drupal_get_path('module', 'nas_menu') . '/plugins/content_types/nas_menu_guide_bar_search/nas_menu_guide_bar_search.js');
}

/**
 * Implements hook_query_TAG_alter.
 *
 * Sort query results by BOA structure order.
 */
function nas_menu_query_boaf_order_alter($query) {
  // Remove current sorting.
  $orderBy = &$query->getOrderBy();
  $orderBy = array();
  // Join to menu_links.
  $query->innerJoin('menu_links', 'ml', 'CONCAT(:node_prefix, node.nid) = ml.link_path AND ml.menu_name = :menu_name', array(
      ':node_prefix' => 'node/',
      ':menu_name' => 'boa',
    ));
  // Order by menu structure.
  $query->orderBy('ml.weight');
}
