<?php

/**
 * @file
 * Customizations of the menu.
 */

/**
 * Implements hook_menu_attribute_info().
 */
function nas_menu_menu_attribute_info_alter(array &$attributes) {
  // Add a Tabindex attribute.
  $attributes['liclass'] = array(
    'label' => t('List item class'),
    'description' => t('Specifies class of LI element.'),
  );

  // Remove the Access Key attribute.
  foreach (array('accesskey', 'title', 'id', 'name', 'rel', 'style', 'target') as $key) {
    unset($attributes[$key]);
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function nas_menu_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme().
 */
function nas_menu_theme() {
  return array(
    'nas_small_header' => array(
      'arguments' => array('menu_tree' => NULL),
      'template' => 'templates/nas-small-header',
    ),
    'nas_don_t_miss' => array(
      'arguments' => array('items' => NULL, 'contextual_links' => NULL),
      'template' => 'templates/nas-don-t-miss',
    ),
    'nas_big_header' => array(
      'arguments' => array(
        'items' => NULL,
        'frontpage_link' => NULL,
        'form' => NULL,
      ),
      'template' => 'templates/nas-big-header',
    ),
    'nas_guide_bar' => array(
      'arguments' => array(
        'div_attributes' => NULL,
        'title' => NULL,
        'preamble' => NULL,
        'logo' => NULL,
        'contextual_links' => NULL,
      ),
      'template' => 'templates/nas-guide-bar',
    ),
  );
}

/**
 * Preprocess function for nas-small-header.tpl.php
 */
function template_nas_small_header(&$vars) {
  $vars['frontpage_url'] = url('<front>');
  $vars['site_name'] = check_plain(variable_get('site_name'));

  $menu_tree = $vars['menu_tree'];

  $items = array();
  foreach ($menu_tree as $menu_item) {
    $item = array(
      'li_class' => isset($menu_item['link']['options']['attributes']['liclass']) ? ' ' . $menu_item['link']['options']['attributes']['liclass'] : '',
      'a_class' => isset($menu_item['link']['options']['attributes']['class']) ? ' ' . implode(' ', $menu_item['link']['options']['attributes']['class']) : '',
      'url' => url($menu_item['link']['link_path']),
      'title' => check_plain($menu_item['link']['link_title']),
    );

    $item['#below'] = array();
    if (!empty($menu_item['below'])) {
      foreach ($menu_item['below'] as $sub_menu_item) {
        $item['#below'][] = array(
          'li_class' => isset($sub_menu_item['link']['options']['attributes']['liclass']) ? ' ' . $sub_menu_item['link']['options']['attributes']['liclass'] : '',
          'a_class' => isset($sub_menu_item['link']['options']['attributes']['class']) ? ' ' . implode(' ', $sub_menu_item['link']['options']['attributes']['class']) : '',
          'url' => url($sub_menu_item['link']['link_path']),
          'title' => check_plain($sub_menu_item['link']['link_title']),
        );
      }
    }

    $items[] = $item;
  }

  $vars['items'] = $items;
}

function nas_menu_search_form($form, &$form_state) {
  $form['search'] = array(
    '#type' => 'textfield',
    '#attributes' => array(
      'placeholder' => array(t('Search the Audubon network')),
      'class' => array('header-search-input', 'radius')
    ),
    '#size' => '',
    '#id' => 'nas-menu-search-input'
  );
  $form['nas_search_btn'] = array(
    '#type' => 'button',
    '#value' => '<i class="icon-magnifier"></i>',
    '#attributes' => array(
      'class' => array('header-search-button', 'button', 'large', 'pea-green')
    ),
  );
  $search_close = l('<i class="icon-close"></i>', '<front>', array(
    'html' => TRUE,
    'attributes' => array(
      'class' => array('hide-for-tiny', 'hide-for-small', 'hide-for-medium', 'header-search-close')
    )
      )
  );
  $form['search_close'] = array(
    '#markup' => $search_close
  );

  return $form;
}

/**
 * Render contextual links for menu
 */
function nas_menu_cl($menu_delta, $additional_links = array()) {
  if (!module_exists('contextual') || !user_access('access contextual links')) {
    return FALSE;
  }
  $contextual_links['#contextual_links']['menu'] = array('admin/structure/menu/manage', array($menu_delta));
  $contextual_links = contextual_pre_render_links($contextual_links);
  if (isset($contextual_links['#links']['menu-edit'])) {
    unset($contextual_links['#links']['menu-edit']);
  }
  if (isset($contextual_links['#links']['menu-list'])) {
    $contextual_links['#links']['menu-list']['title'] = t('edit links');
  }
  $build = array(
    '#prefix' => '<div class="contextual-links-wrapper">',
    '#suffix' => '</div>',
    '#theme' => 'links__contextual',
    '#links' => array_merge($contextual_links['#links'], $additional_links),
    '#attributes' => array('class' => array('contextual-links')),
    '#attached' => array(
      'library' => array(array('contextual', 'contextual-links')),
    ),
  );

  return drupal_render($build);
}