<?php

/**
 * @file
 * Install/uninstall and update functions for the NAS i18n redirect module.
 */

/**
 * Implements hook_install().
 */
function nas_i18n_redirect_install() {
  db_update('system')
    ->fields(array('weight' => 100))
    ->condition('type', 'module')
    ->condition('name', 'nas_i18n_redirect')
    ->execute();
}

/**
 * NAS i18n_redirect should process after the redirect module hook_init().
 */
function nas_18n_redirect_update_7001() {
  nas_i18n_redirect_install();
}
