<?php

/**
 * @file
 * NAS Internationalization (i18n) module.
 *
 * Redirect to node language path when prefix is missed.
 */

/**
 * Implements hook_help().
 */
function nas_i18n_redirect_help($path, $arg) {
  switch ($path) {
    case 'admin/config/regional/i18n':
      if (!module_exists('i18n_node')) {
        $output = '<p>' . t('To have <em>Translation redirect</em> working with your content you should <a href="@admin_modules">enable the <em>Multilingual content</em> module</a>.', array('@admin_modules' => url('admin/modules'))) . '</p>';
        return $output;
      }
  }
}

/**
 * Implements hook_init().
 */
function nas_i18n_redirect_init() {
  $path = $_GET['q'];
  $language = i18n_language_interface();
  $default_language = language_default();
  if (!$path) {
    return;
  }
  if (in_array($path, variable_get('nas_i18n_redirect_ignore', array()))) {
    return;
  }
  elseif ($translations = i18n_get_path_translations($path)) {

    if (isset($translations[$language->language]) && $translations[$language->language]['href'] != $path) {
      drupal_goto($translations[$language->language]['href'], array('language' => $language, 'query' => drupal_get_query_parameters()), 301);
    }
  }
  elseif ($language->language != $default_language->language && !_nas_i18n_redirect_prevent($path)) {
    _nas_i18n_redirect_show_language_message();
    if ($path == variable_get('site_frontpage', 'node')) {
      $path = '';
    }
    drupal_goto($path, array('language' => $default_language, 'query' => drupal_get_query_parameters()), 301);
  }
}

/**
 * Helper function to check if we should prevent redirect.
 */
function _nas_i18n_redirect_prevent($path) {
  // We should redirect only GET requests.
  if ($_SERVER['REQUEST_METHOD'] != 'GET') {
    return TRUE;
  }

  // We should redirect only for the site default theme.
  global $theme;
  $theme_default = variable_get('theme_default', 'bartik');
  if ($theme_default != $theme) {
    return TRUE;
  }

  // Exclusions for special GET requests.
  $exclusions = array(
    'ajax/audubon-near-you',
    'rss.xml',
  );
  if (in_array($path, $exclusions)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Helper function to set a flag that we need to show language message.
 */
function _nas_i18n_redirect_show_language_message() {
  global $base_path;
  setcookie('nas_language_message', 1, NULL, $base_path);
}
