<?php

/**
 * @file
 * Maintains a cloning and scheduling of panel pages.
 */

/**
 * Implements hook_menu().
 */
function nas_page_scheduler_menu() {
  $items = array();

  $items['page/%ctools_js/clone/%'] = array(
    'page callback' => 'nas_page_scheduler_page_clone',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/content/nas/page_scheduler/start'] = array(
    'title' => 'Run Page Scheduler check',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nas_page_scheduler_check_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/content/nas/page_scheduler/list'] = array(
    'title' => 'Scheduled landing pages',
    'page callback' => 'nas_page_scheduler_list',
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_cron_job_scheduler_info().
 */
function nas_page_scheduler_cron_job_scheduler_info() {
  $schedulers = array();
  $schedulers['nas_page_scheduler_check_task'] = array(
    'worker callback' => 'nas_page_scheduler_start',
  );
  return $schedulers;
}

/**
 * Page callback for page "Scheduled landing pages".
 */
function nas_page_scheduler_list() {
  $pages = nas_page_scheduler_get_pages_list();

  foreach ($pages as &$page) {
    if (isset($page->conf['nas_page_scheduler_original_page_task_name']) &&
      $page->conf['nas_page_scheduler_original_page_task_name'] &&
      isset($page->conf['nas_page_scheduler_date_publish']) &&
      isset($page->conf['nas_page_scheduler_page_published']) &&
      !$page->conf['nas_page_scheduler_page_published']) {

      $page_load = page_manager_cache_load('page-' . $page->subtask);

      $name = $page_load->subtask['admin title'];
      $publish_date = date('Y-m-d H:i', $page->conf['nas_page_scheduler_date_publish']);
      $classes = array();
      $rows[] = array(
        'data' => array(
          array('data' => $name),
          array('data' => $publish_date),
          array(
            'data' => l(t('Edit'), 'admin/structure/pages/edit/page-' . $page->subtask, array(
              'attributes' => array(
                'target' => '_blank',
              ),
            )),
          ),
        ),
        'class' => $classes,
      );
    }
  }
  
  $output = t('There are no scheduled pages yet.');
  if (!empty($rows)) {
    // Build table with all scheduled pages.
    $header = array(
      array('data' => t('Admin title')),
      array('data' => t('Publish on')),
      array('data' => t('')),
    );
    $output = theme('table', array(
      'header' => $header,
      'rows' => $rows,
    ));
  }

  return $output;
}

/**
 * Function to get all pages with.
 */
function nas_page_scheduler_get_pages_list() {
  // Now check all panel pages and ignore all mini panels
  ctools_include('page', 'page_manager', 'plugins/tasks');
  ctools_include('page_manager.admin', 'page_manager', '');
  ctools_include('export');
   
  $tasks = page_manager_get_tasks_by_type('page');
  $pages_with_scheduling = $page_types = array();
   
  foreach ($tasks as $task) {
    // Disabled page return empty
    if ($pages = page_manager_load_task_handlers($task)) {
      $page_types[] = $pages;
    }
  }
   
  // Not all display objects are loaded, make sure to load them
  foreach ($page_types as &$pages) {
    foreach ($pages as &$page) {
      if (empty($page->conf['display']) && !empty($page->conf['did'])) {
        $page->conf['display'] = panels_load_display($page->conf['did']);
        if (!empty($page->conf['nas_page_scheduler_state'])) {
          $pages_with_scheduling[] = $page;
        }
      }
    }
  }

  return $pages_with_scheduling;
}

/**
 * Page callback for modal "Schedule new version of the page".
 */
function nas_page_scheduler_page_clone() {
  ctools_include('modal');
  ctools_include('ajax');
  $form_state = array(
    'title' => t('Schedule new version of the page'),
    'ajax' => TRUE,
  );
  $output = ctools_modal_form_wrapper('nas_page_scheduler_settings_form', $form_state);
  print ajax_render($output);
}

/**
 * Form nas_page_scheduler_settings_form.
 */
function nas_page_scheduler_settings_form($form, &$form_state) {
  $form['date_publish'] = array(
    '#type' => 'date_popup',
    '#default_value' => date('Y-m-d H:i:s'),
    '#date_type' => DATE_DATETIME,
    '#date_timezone' => date_default_timezone(),
    '#date_format' => 'm-d-Y H:i',
    '#date_increment' => 1,
    '#date_year_range' => '0:+3',
    '#required' => TRUE,
  );
  $form['subtask'] = array(
    '#type' => 'hidden',
    '#default_value' => arg(3),
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
    '#attributes' => array(
      'class' => array('button', 'tomato', 'large'),
    ),
  );
  $form['cancel'] = array(
    '#type' => 'submit',
    '#value' => t('Cancel'),
    '#attributes' => array(
      'class' => array('ctools-close-modal', 'button', 'tomato', 'large'),
    ),
  );
  return $form;
}

/**
 * nas_page_scheduler_settings_form validation callback.
 */
function nas_page_scheduler_settings_form_validate($form, &$form_state) {
  if (!empty($form_state['values']['date_publish'])) {
    $form_state['values']['date_publish'] = date_create($form_state['values']['date_publish'])->getTimestamp();
  }
  else {
    form_set_error('date_publish', t('Please specify publish date'));
  }
}

/**
 * nas_page_scheduler_settings_form submit callback.
 */
function nas_page_scheduler_settings_form_submit($form, $form_state) {
  $page = page_manager_cache_load('page-' . $form_state['values']['subtask']);
  $original = $page->subtask['subtask'];

  // Unique hash for path and machine name.
  $hash = substr(md5(rand()), 0, 6);
  $machine_name = preg_replace('/version(.*)/', 'version' . $hash, $form_state['values']['subtask']);
  if ($machine_name == $form_state['values']['subtask']) {
    $machine_name = $form_state['values']['subtask'] . '_version' . $hash;
  }
  $original->name = $machine_name;
  $original->admin_title = $page->subtask['subtask']->admin_title;
  $original->path = $hash;
  // Hide page from anonymous until get it published.
  $original->access['plugins'][] = array(
    'name' => 'role',
    'settings'=> array(
      'rids' => array(
        0 => 1,
      ),
    ),
    'context'=> 'logged-in-user',
    'not' => TRUE,
  );

  $handlers = !empty($page->handlers) ? $page->handlers : FALSE;

  foreach ($handlers as $key => $handler) {
    // Scheduled page is not an original.
    $handler->conf['nas_page_scheduler_original_page'] = FALSE;
    // Save the original task name.
    $handler->conf['nas_page_scheduler_original_page_task_name'] = 'page-' . $form_state['values']['subtask'];
    // Save date.
    $handler->conf['nas_page_scheduler_date_publish'] = $form_state['values']['date_publish'];
    // Status.
    $handler->conf['nas_page_scheduler_page_published'] = FALSE;
  }

  // Export the handler, which is a fantastic way to clean database IDs out of it.
  $export = page_manager_page_export($original, $handlers);
  ob_start();
  eval($export);
  ob_end_clean();

  $task_name = page_manager_make_task_name('page', $page->name);
  $cache = new stdClass();

  page_manager_page_new_page_cache($page, $cache);
  page_manager_set_page_cache($cache);

  $commands[] = ctools_ajax_command_redirect(page_manager_edit_url($task_name));
  print ajax_render($commands);
  exit;
}

/**
 * Implements hook_page_manager_variant_operations_alter().
 *
 * Shameful rip off from panels_everywhere module.
 *
 * @see panels_everywhere_page_manager_variant_operations_alter()
 * @see http://groups.drupal.org/node/110719#comment-356094
 */
function nas_page_scheduler_page_manager_variant_operations_alter(&$operations, $handler) {
  // Use this obnoxious construct to safely insert our item.
  reset($operations['children']);
  $children_operations = array();
  while (list($key, $value) = each($operations['children'])) {
    $children_operations[$key] = $value;
    if ($key == 'context') {
      $children_operations['scheduler'] = array(
        'title' => t('Scheduler'),
        'description' => t('Edit publish dates for this page.'),
        'form' => 'nas_page_scheduler_variant_scheduler_form',
      );
    }
  }
  $operations['children'] = $children_operations;
}

/**
 * Panels scheduler configuration form.
 */
function nas_page_scheduler_variant_scheduler_form($form, &$form_state) {
  ctools_include('context-task-handler');

  $handler = $form_state['handler'];
  $contexts = ctools_context_handler_get_all_contexts($form_state['task'], $form_state['subtask'], $handler);

  $form += nas_page_scheduler_partial_configuration_form($handler->conf, $contexts);

  return $form;
}

/**
 * Implements hook_ctools_render_alter().
 *
 * When a Page Manager page is rendered, build the Scheduler link if it exists.
 */
function nas_page_scheduler_ctools_render_alter(&$info, &$page, &$context) {
  $handler = $context['handler'];
  $contexts = ctools_context_handler_get_handler_contexts($context['contexts'], $handler);
  if (isset($handler->conf['nas_page_scheduler_state']) && $handler->conf['nas_page_scheduler_state'] && user_access('access administration pages')) {
    if (isset($handler->task) && $handler->task == 'page') {
      $info['content'] = l(theme('image', array(
          'path' => drupal_get_path('theme', 'nas') . '/img/clock-icon.png',
        )), 'page/nojs/clone/' . $handler->subtask, array(
        'attributes' => array(
          'class' => array(
            'ctools-use-modal',
            'schedule-new-version',
          ),
          'title' => t('Schedule new version'),
        ),
        'html' => TRUE,
      )) . $info['content'];
    }
  }
}

/**
 * Returns a partially formed configuration form.
 *
 * @param $conf
 * @param $contexts
 * @return
 *  An array containing a partial configuration form.
 */
function nas_page_scheduler_partial_configuration_form($conf, $contexts) {
  $disabled = TRUE;
  if (!isset($conf['nas_page_scheduler_original_page']) || $conf['nas_page_scheduler_original_page']) {
    $disabled = FALSE;
  }
  $form['settings']['nas_page_scheduler_state'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable scheduler configuration.'),
    '#default_value' => isset($conf['nas_page_scheduler_state']) ? $conf['nas_page_scheduler_state'] : FALSE,
    '#disabled' => $disabled,
  );
  $form['settings']['nas_page_scheduler_original_page'] = array(
    '#type' => 'hidden',
    '#default_value' => isset($conf['nas_page_scheduler_original_page']) ? $conf['nas_page_scheduler_original_page'] : TRUE,
  );
  if (!empty($conf['nas_page_scheduler_state']) &&
    isset($conf['nas_page_scheduler_original_page']) &&
    !$conf['nas_page_scheduler_original_page'] &&
    isset($conf['nas_page_scheduler_date_publish'])) {

    $form['settings']['nas_page_scheduler_date_publish'] = array(
      '#type' => 'date_popup',
      '#default_value' => isset($conf['nas_page_scheduler_date_publish']) ? date('Y-m-d H:i:s', $conf['nas_page_scheduler_date_publish']) : date('Y-m-d H:i:s'),
      '#date_type' => DATE_DATETIME,
      '#date_timezone' => date_default_timezone(),
      '#date_format' => 'm-d-Y H:i',
      '#date_increment' => 1,
      '#date_year_range' => '0:+3',
    );
  }

  return $form;
}

/**
 * Validation callback handler for panels scheduler configuration form.
 */
function nas_page_scheduler_variant_scheduler_form_validate($form, &$form_state) {
  if (!empty($form_state['values']['nas_page_scheduler_date_publish'])) {
    $form_state['values']['nas_page_scheduler_date_publish'] = date_create($form_state['values']['nas_page_scheduler_date_publish'])->getTimestamp();
  }
  elseif ($form_state['values']['nas_page_scheduler_original_page']) {
    return;
  }
  else {
    form_set_error('nas_page_scheduler_date_publish', t('Please specify publish date'));
  }
}

/**
 * Submission callback handler for panels scheduler configuration form.
 */
function nas_page_scheduler_variant_scheduler_form_submit($form, &$form_state) {
  if (!empty($form_state['values']['nas_page_scheduler_date_publish'])) {
    $form_state['handler']->conf['nas_page_scheduler_date_publish'] = $form_state['values']['nas_page_scheduler_date_publish'];
  }
  $form_state['handler']->conf['nas_page_scheduler_state'] = (bool) $form_state['values']['nas_page_scheduler_state'];
  $form_state['handler']->conf['nas_page_scheduler_original_page'] = (bool) $form_state['values']['nas_page_scheduler_original_page'];
}

/**
 * Callback form for nas/page_scheduler/start page.
 */
function nas_page_scheduler_check_form($form, &$form_state) {
  drupal_set_message('Current server time is ' . date('m-d-Y H:i:s', REQUEST_TIME));
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Start'),
  );
  return $form;
}

/**
 * Submit form for nas/page_scheduler/start page.
 */
function nas_page_scheduler_check_form_submit($form, &$form_state) {
  nas_page_scheduler_start();
  return $form;
}

function nas_page_scheduler_start() {
  $pages = nas_page_scheduler_get_pages_list();

  foreach ($pages as $page) {
    if (isset($page->conf['nas_page_scheduler_original_page_task_name']) &&
      $page->conf['nas_page_scheduler_original_page_task_name'] &&
      isset($page->conf['nas_page_scheduler_page_published']) &&
      !$page->conf['nas_page_scheduler_page_published']) {

      $original_page = page_manager_cache_load($page->conf['nas_page_scheduler_original_page_task_name']);
      $scheduled_page = page_manager_cache_load('page-' . $page->subtask);

      if (empty($scheduled_page->subtask_id)) {
        continue;
      }

      // Unique hash.
      $hash = substr(md5(rand()), 0, 6);

      foreach ($scheduled_page->handlers as $key => $handler) {
        $date_publish = $handler->conf['nas_page_scheduler_date_publish'];
        $changed = FALSE;

        if ($date_publish <= REQUEST_TIME) {
          // We have to ensure that original page is loaded.
          if (empty($original_page->subtask_id)) {
            // Try to load current published page instead.
            foreach ($pages as $page) {
              if (isset($page->conf['nas_page_scheduler_page_published']) &&
                $page->conf['nas_page_scheduler_page_published'] &&
                $page->conf['nas_page_scheduler_original_page_task_name'] == 
                $scheduled_page->handlers[$handler->name]->conf['nas_page_scheduler_original_page_task_name']) {

                $original_page = page_manager_cache_load('page-' . $page->subtask);
              }
            }
          }

          // Modify scheduled page.
          $scheduled_page->subtask['subtask']->path = $original_page->subtask['subtask']->path;
          $scheduled_page->handlers[$handler->name]->conf['nas_page_scheduler_page_published'] = TRUE;
          $scheduled_page->handlers[$handler->name]->conf['nas_page_scheduler_original_page'] = TRUE;
          $scheduled_page->handlers[$handler->name]->conf['nas_page_scheduler_original_page_task_name'] = $original_page->task_name;
          // Remove previously added access plugin.
          foreach ($scheduled_page->subtask['subtask']->access['plugins'] as $key => $plugin) {
            if ($plugin['name'] == 'role') {
              unset($scheduled_page->subtask['subtask']->access['plugins'][$key]);
            }
          }
          // Mark handler as changed.
          $scheduled_page->handler_info[$handler->name]['changed'] |= PAGE_MANAGER_CHANGED_CACHED;
          // Modify original page.
          $original_page->subtask['subtask']->path = $hash;
          $original_page->subtask['disabled'] = TRUE;
          foreach ($original_page->handlers as $key => $handler) {
            $original_page->handlers[$handler->name]->conf['nas_page_scheduler_original_page'] = FALSE;
            // Mark handler as changed.
            $original_page->handler_info[$handler->name]['changed'] |= PAGE_MANAGER_CHANGED_CACHED;
          }
          $access_plugin = array(
            'name' => 'role',
            'settings'=> array(
              'rids' => array(
                0 => 1,
              ),
            ),
            'context'=> 'logged-in-user',
            'not' => TRUE,
          );
          if (empty($original_page->subtask['subtask']->access['plugins'])) {
            $original_page->subtask['subtask']->access['plugins'][] = $access_plugin;
          }
          else {
            foreach ($original_page->subtask['subtask']->access['plugins'] as $key => $plugin) {
              if ($plugin['name'] == 'role') {
                $original_page->subtask['subtask']->access['plugins'][$key] = $access_plugin;
              }
            }
          }
          $clear_cache = $changed = $delete_page = TRUE;
        }
      }
      if ($changed) {
        // Finally save all changes to the original and scheduled pages.
        page_manager_set_page_cache($scheduled_page);
        if ($cache = page_manager_get_page_cache('page-' . $scheduled_page->subtask_id)) {
          page_manager_save_page_cache($cache);
        }

        page_manager_set_page_cache($original_page);
        if ($cache = page_manager_get_page_cache('page-' . $original_page->subtask_id)) {
          page_manager_save_page_cache($cache);
        }

        // Delete page in case it has normal storage.
        if (isset($delete_page) && $delete_page && $original_page->subtask['subtask']->type == t('Normal')) {
          page_manager_page_delete($original_page->subtask['subtask']);
        }

        drupal_set_message('"' . $scheduled_page->subtask['admin title'] . '" has been published.');
      }
    }
  }
  if ($clear_cache) {
    drupal_flush_all_caches();
  }
  else {
    drupal_set_message('There are no pages to publish.');
  }
}
