<?php
/**
 * @file
 * Code related to tiled BOA plates.
 */

/**
 * Implements hook_menu().
 */
function nas_boa_plates_menu() {
  $items = array();
  $items['node/%node/plate'] = array(
    'page callback' => 'nas_boa_plates_page',
    'page arguments' => array(1),
    'access callback' => 'nas_boa_plates_page_access',
    'access arguments' => array(1),
    'delivery callback' => 'ajax_deliver',
    'file' => 'nas_boa_plates.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Page access callback.
 */
function nas_boa_plates_page_access($node) {
  return $node->type == 'boa';
}

/**
 * Implements hook_node_view().
 */
function nas_boa_plates_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'boa' && $view_mode == 'full') {
    _nas_boa_plates_doheader();
  }
}

/**
 * Loads the various js and css files.
 */
function _nas_boa_plates_doheader() {
  $already_added = &drupal_static('nas_boa_plates_js');
  // Don't add the JavaScript and CSS multiple times.
  if (isset($already_added)) {
    return;
  }
  $already_added = TRUE;

  // Include the CTools tools that we need.
  ctools_include('ajax');
  ctools_include('modal');

  // Add CTools' javascript to the page.
  ctools_modal_add_js();

  $js_settings = array(
    'boa-plate' => array(
      'modalSize' => array(
        'type' => 'scale',
        'width' => 0.9,
        'height' => 0.9,
        'contentRight' => 0,
        'contentBottom' => 0,
      ),
      'modalOptions' => array(
        'opacity' => 0.85,
        'background-color' => '#000',
      ),
      'animation' => 'fadeIn',
      'modalTheme' => 'BOAPlateModal',
      'closeText' => t('Close'),
    ),
    'boadeepzoom' => array(
      'path' => '//d2e5ib4b6clnb8.cloudfront.net',
    ),
  );

  drupal_add_js($js_settings, 'setting');

  // Add own js and CSS.
  ctools_add_js('modals', 'nas_boa_plates');
}

/**
 * Implements hook_js_alter().
 */
function nas_boa_plates_js_alter(&$javascript) {
  $already_added = &drupal_static('nas_boa_plates_js');
  if ($already_added) {
    unset($javascript[drupal_get_path('module', 'deepzoom') . '/engines/deepzoom.openseadragon.js']);
  }
  $internal_path = 'sites/all/libraries/openseadragon/openseadragon.min.js';
  if (isset($javascript[$internal_path])) {
    $external_path = 'https://d2e5ib4b6clnb8.cloudfront.net/openseadragon/openseadragon.min.js';
    $javascript[$external_path] = $javascript[$internal_path];
    $javascript[$external_path]['data'] = $external_path;
    $javascript[$external_path]['type'] = 'external';
    unset($javascript[$internal_path]);
  }
}
