<?php

/**
 * @file
 * Maintains panel panes.
 */

define('NAS_PANES_BIRD_GUIDE_PAGE_MANAGER_CACHE_KEY', 'page-bird_guide');
define('NAS_PANES_BIRD_LANDING_PAGE_MANAGER_CACHE_KEY', 'page-birds_landing');
define('NAS_PANES_FRONTPAGE_PAGE_MANAGER_CACHE_KEY', 'page-frontpage2');
define('NAS_PANES_NEWS_PAGE_MANAGER_CACHE_KEY', 'page-news');
define('NAS_PANES_FLYWAY_LANDING_PAGE_MANAGER_CACHE_KEY', 'page-flyways_landing');
define('NAS_PANES_NODE_VIEW_PAGE_MANAGER_CACHE_KEY', 'node_view');
define('NAS_PANES_PANELIZER_NODE_VIEW_PAGE_MANAGER_CACHE_KEY', 'panelizer:node:');

define('NAS_FEATURED_BIRD_IMAGE_STYLE', 'featured_bird');
define('NAS_FEATURED_BIRD_IMAGE_STYLE_MOBILE', 'featured_bird_mobile');
define('NAS_FEATURED_FRONTPAGE_IMAGE_STYLE', 'featured_frontpage');
define('NAS_FEATURED_FRONTPAGE_ARTICLE_IMAGE_STYLE', 'frontpage_featured_article_image');
define('NAS_FEATURED_ILLUSTRATION_IMAGE_STYLE', 'featured_bird_illustration');
define('NAS_GET_OUTSIDE_IMAGE_STYLE', 'get_outside');

define('NAS_FLYWAYS_NUMBER', 4);

/**
 * Implements hook_ctools_plugin_directory().
 */
function nas_panes_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && !empty($plugin_type)) {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_theme().
 */
function nas_panes_theme() {
  $theme = array(
    'article_more_features' => array(
      'variables' => array(
        'teasers' => NULL,
        'title' => '',
        'more_link' => '',
        'contextual_links' => '',
      ),
      'template' => 'article-more-features',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/article_more_features',
    ),
    'boa_hero' => array(
      'variables' => array(
        'image' => '',
        'next_url' => '',
        'prev_url' => '',
      ),
      'template' => 'boa-hero',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/boa_hero',
    ),
    'nas_featured_bird' => array(
      'variables' => array(
        'name' => '',
        'scientific_name' => '',
        'url' => '',
        'image_path' => '',
        'image_path_mobile' => '',
        'image_string' => '',
        'illustration_path' => '',
        'color' => '',
        'contextual_links' => '',
      ),
      'template' => 'nas-featured-bird',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/featured_bird'
    ),
    'nas_bird_landing_featured' => array(
      'variables' => array(
        'name' => '',
        'url' => '',
        'image_path' => '',
        'image_path_mobile' => '',
        'summary' => '',
        'bird_guide_link' => '',
        'category' => '',
        'color' => '',
        'category_link' => '',
        'category_link_more' => '',
        'contextual_links' => '',
      ),
      'template' => 'bird-landing-featured',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/bird_landing_featured'
    ),
    'nas_frontpage_featured' => array(
      'variables' => array(
        'image_caption' => '',
        'image_credit' => '',
        'summary' => '',
        'title_link' => '',
        'blue_text_link' => '',
        'contextual_links' => '',
      ),
      'template' => 'frontpage-featured',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/frontpage_featured'
    ),
    'nas_frontpage_featured_mobile' => array(
      'variables' => array(
        'image_path' => '',
        'summary' => '',
        'title_link' => '',
        'blue_text_link' => '',
        'contextual_links' => '',
      ),
      'template' => 'frontpage-featured-mobile',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/frontpage_featured'
    ),
    'nas_frontpage_featured_article' => array(
      'variables' => array(
        'image_path' => '',
        'conversation_link' => '',
        'article_raw_link' => '',
        'article_link' => '',
        'tagline_text' => '',
        'contextual_links' => '',
      ),
      'template' => 'frontpage-featured-article',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/frontpage_featured_article'
    ),
    'nas_in_the_news' => array(
      'variables' => array(
        'teasers' => NULL,
        'title' => '',
      ),
      'template' => 'nas-in-the-news',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/in_the_news'
    ),
    'flyway_in_the_news' => array(
      'variables' => array(
        'teasers' => NULL,
        'title' => '',
        'more_link' => '',
      ),
      'template' => 'flyway-in-the-news',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/flyway_in_the_news'
    ),
    'flyway_conservation_projects' => array(
      'variables' => array(
        'teasers' => NULL,
        'title' => '',
        'more_link' => '',
      ),
      'template' => 'flyway-conservation-projects',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/flyway_conservation_projects'
    ),
    'nas_panes_pane_donate_button' => array(
      'variables' => array(
        'caption' => '',
        'link' => '',
      ),
      'template' => 'nas-panes-pane-donate-button',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/donate_button'
    ),
    'nas_featured_social_in_article' => array(
      'variables' => array(
        'title' => '',
        'page_link' => '',
      ),
      'template' => 'nas-featured-social-in-article',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/block_in_article'
    ),
    'nas_panes_social_news_block' => array(
      'variables' => array(
        'title' => '',
        'page_link' => '',
        'caption' => '',
      ),
      'template' => 'nas-panes-social-news-block',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/news_social_block'
    ),
    'nas_panes_press_contact' => array(
      'variables' => array(
        'title' => '',
        'contacts' => array(),
      ),
      'template' => 'nas-panes-press-contact',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/press_contact'
    ),
    'nas_panes_press_releases' => array(
      'variables' => array(
        'title' => '',
        'releases' => array(),
      ),
      'template' => 'nas-panes-press-releases',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/press_releases'
    ),
    'nas_panes_article_section' => array(
      'variables' => array(
        'url' => '',
        'text' => '',
        'link_classes' => '',
      ),
      'template' => 'article-section',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/article_section',
    ),
    'nas_flyways_landing_top' => array(
      'variables' => array(
        'title' => '',
        'subtitle' => '',
        'hero_image' => '',
        'bottomtitle' => '',
        'flyway' => '',
      ),
      'template' => 'flyways-landing-top',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/flyways_landing_top'
    ),
    'nas_flyways_landing_middle' => array(
      'variables' => array(
        'flyway' => array(),
        'contextual_links' => '',
      ),
      'template' => 'flyways-landing-middle',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/flyways_landing_middle'
    ),
    'nas_flyways_landing_bottom' => array(
      'variables' => array(
        'flyway' => array(),
        'contextual_links' => '',
      ),
      'template' => 'flyways-landing-bottom',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/flyways_landing_bottom'
    ),
    'nas_flyways_landing_three_columns' => array(
      'variables' => array(
        'columns' => array(),
        'contextual_links' => '',
      ),
      'template' => 'flyways-landing-three-columns',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/flyways_landing_three_columns'
    ),
    'frontpage_in_the_news' => array(
      'variables' => array(
        'teasers' => array(),
        'title' => '',
        'bird_guide_link' => '',
        'bird_guide_title' => '',
      ),
      'template' => 'frontpage-in-the-news',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/frontpage_in_the_news'
    ),
    'nas_flyways_partners' => array(
      'variables' => array(
        'title' => '',
        'background_image' => '',
        'summary' => '',
        'read_more_link' => '',
      ),
      'template' => 'flyways-partners',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/flyways_partners'
    ),
    'nas_get_outside' => array(
      'template' => 'nas-get-outside',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/get_outside'
    ),
    'frontpage_editorial_cards' => array(
      'template' => 'frontpage-editorial-cards',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/frontpage_editorial_cards'
    ),
    'static_page_menu' => array(
      'template' => 'static-page-menu',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/static_page_menu',
    ),
    'magazine_issue_featured' => array(
      'template' => 'magazine-issue-featured',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/magazine_issue_featured',
    ),
    'magazine_issue_other_issues' => array(
      'template' => 'magazine-issue-other-issues',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/magazine_issue_other_issues',
    ),
    'project_birds' => array(
      'template' => 'project-birds',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/project_birds',
    ),
    'other_projects' => array(
      'template' => 'other-projects',
      'path' => drupal_get_path('module', 'nas_panes') . '/plugins/content_types/other_projects',
    ),
  );

  for ($i = 1; $i <= NAS_FLYWAYS_NUMBER; $i++) {
    $theme['variables']['nas_flyways_landing_top']['flyway'][$i] = array();
    $theme['variables']['nas_flyways_landing_middle']['flyway'][$i] = array();
  }

  for ($i = 1; $i <=3; $i++) {
    $theme['variables']['nas_flyways_landing_three_columns']['columns'][$i] = array();
  }

  return $theme;
}

/**
 * Implements hook_ajax_render_alter().
 */
function nas_panes_ajax_render_alter(&$commands) {

  $copy_commands = $commands;
  $last_command = array_pop($copy_commands);
  // Will get triggered when user submitted the form.
  if (strpos($_GET['q'], '/form') !== FALSE && $last_command['command'] == 'modal_dismiss') {
    // Here we save the cache to database. When we edited the pane we made
    // changes in the cache. In order the page to see the changes we need
    // to save cache data to database.
    if (strpos($_GET['q'], NAS_PANES_BIRD_GUIDE_PAGE_MANAGER_CACHE_KEY) !== FALSE) {
      nas_panes_save_bird_guide_pane();
    }

    if (strpos($_GET['q'], NAS_PANES_BIRD_LANDING_PAGE_MANAGER_CACHE_KEY) !== FALSE) {
      nas_panes_save_bird_landing_page();
    }

    if (strpos($_GET['q'], NAS_PANES_FRONTPAGE_PAGE_MANAGER_CACHE_KEY) !== FALSE) {
      nas_panes_save_frontpage_page();
    }

    if (strpos($_GET['q'], NAS_PANES_NEWS_PAGE_MANAGER_CACHE_KEY) !== FALSE) {
      nas_panes_save_news_page();
    }

    if (strpos($_GET['q'], NAS_PANES_NODE_VIEW_PAGE_MANAGER_CACHE_KEY) !== FALSE) {
      nas_panes_save_node_view_page();
    }

    if (strpos($_GET['q'], NAS_PANES_PANELIZER_NODE_VIEW_PAGE_MANAGER_CACHE_KEY) !== FALSE) {
      // arg(4) is cache key like panelizer:node:%nid:page_manager.
      $cache_key = arg(4);
      // Get panel cache.
      $cache = panels_edit_cache_get($cache_key);
      // Write it to DB.
      panels_save_display($cache->display);
    }

    if (strpos($_GET['q'], NAS_PANES_FLYWAY_LANDING_PAGE_MANAGER_CACHE_KEY) !== FALSE) {
      nas_panes_save_flyways_landing_page();
    }

    $commands[] = ctools_ajax_command_reload();
  }
}

/**
 * Resave bird guide page (cache to database).
 */
function nas_panes_save_bird_guide_pane() {
  $cache = page_manager_get_page_cache(NAS_PANES_BIRD_GUIDE_PAGE_MANAGER_CACHE_KEY);
  page_manager_save_page_cache($cache);
}

/**
 * Resave bird landing page (cache to database).
 */
function nas_panes_save_bird_landing_page() {
  $cache = page_manager_get_page_cache(NAS_PANES_BIRD_LANDING_PAGE_MANAGER_CACHE_KEY);
  page_manager_save_page_cache($cache);
}

/**
 * Resave frontpage page (cache to database).
 */
function nas_panes_save_frontpage_page() {
  $cache = page_manager_get_page_cache(NAS_PANES_FRONTPAGE_PAGE_MANAGER_CACHE_KEY);
  page_manager_save_page_cache($cache);
}

/**
 * Resave news page (cache to database).
 */
function nas_panes_save_news_page() {
  $cache = page_manager_get_page_cache(NAS_PANES_NEWS_PAGE_MANAGER_CACHE_KEY);
  page_manager_save_page_cache($cache);
}

/**
 * Resave news page (cache to database).
 */
function nas_panes_save_flyways_landing_page() {
  $cache = page_manager_get_page_cache(NAS_PANES_FLYWAY_LANDING_PAGE_MANAGER_CACHE_KEY);
  page_manager_save_page_cache($cache);
}

/**
 * Resave bird node view page (cache to database).
 */
function nas_panes_save_node_view_page() {
  $cache = page_manager_get_page_cache(NAS_PANES_NODE_VIEW_PAGE_MANAGER_CACHE_KEY);
  $cache->changes = array(
    'handlers' => TRUE,
    'handlers/node_view_panel_context' => TRUE,
    'handlers/node_view_panel_context/content' => TRUE,
  );
  $cache->changed = TRUE;
  $cache->handler_info['node_view_panel_context']['changed'] = 2;

  page_manager_save_page_cache($cache);
}

/**
 * Implements hook_ctools_plugin_post_alter().
 *
 * Remove "Edit Panel" contextual link form all panels pages.
 */
function nas_panes_ctools_plugin_post_alter(&$plugin, &$info) {
  if ($info['type'] == 'task_handlers') {
    $plugin['contextual link'] = 'return';
  }
}

/**
 * Get blue text link of the node (article).
 */
function nas_panes_get_blue_text_link($node) {
  $custom_section_item = field_get_items('node', $node, 'field_custom_section');
  if (!empty($custom_section_item)) {
    $term = taxonomy_term_load($custom_section_item[0]['tid']);
    return array(check_plain($term->name), url('taxonomy/term/' . $term->tid));
  }

  $menu_section_item = field_get_items('node', $node, 'field_menu_section');
  if (!empty($menu_section_item)) {
    // Default is the first term.
    $term = taxonomy_term_load($menu_section_item[0]['tid']);

    $term_tids = array();
    foreach ($menu_section_item as $item) {
      $term_tids[] = $item['tid'];
    }
    $terms = taxonomy_term_load_multiple($term_tids);
    $term_name_keyed = array();
    foreach ($terms as $term) {
      $term_name_keyed[$term->name] = $term;
    }
    $term_names = array_keys($term_name_keyed);

    $trail = menu_get_active_trail();
    $trail = array_reverse($trail);
    foreach ($trail as $menu_item) {
      if (in_array($menu_item['title'], $term_names)) {
        $term = $term_name_keyed[$menu_item['title']];
        break;
      }
    }
    return array(check_plain($term->name), url('taxonomy/term/' . $term->tid));
  }
  return array(NULL, NULL);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nas_panes_preprocess_nas_bird_landing_featured(&$variables) {
  $variables['color_text'] = $variables['color'] == 'dark' ? 'light' : 'dark';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nas_panes_preprocess_nas_featured_bird(&$variables) {
  $variables['color_text'] = $variables['color'] == 'dark' ? 'light' : 'dark';
}

/**
 * Preprocess
 */
function nas_panes_preprocess_nas_flyways_landing_bottom(&$vars) {
  foreach ($vars['flyway'] as &$flyway) {
    $flyway['name_id'] = preg_replace('/[^a-z]/', '-', strtolower($flyway['name']));
  }
}

/**
 * Implements hook_nas_after_import().
 *
 * Add related bird to four articles for the frontpage.
 */
function nas_panes_nas_after_import() {
  $article_results = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('n.type', 'article')
    ->orderRandom()
    ->range(0, 4)
    ->execute()->fetchAll();
  $bird_results = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('n.type', 'bird')
    ->orderRandom()
    ->range(0, 4)
    ->execute()->fetchAll();
  foreach ($article_results as $key => $result) {
    $article = node_load($result->nid);
    $article->field_related_bird = array(
      LANGUAGE_NONE => array(
        array('target_id' => $bird_results[$key]->nid),
      ),
    );
    node_save($article);
  }
}

/**
 * Get the Next BOA node.
 */
function nas_panes_boa_next($node) {
  if ($node->nid == nas_panes_boa_max()) {
    return nas_panes_boa_min();
  }

  $plate_number_items = field_get_items('node', $node, 'field_boa_plate');
  $plate_number = 0;
  if (!empty($plate_number_items)) {
    $plate_number = $plate_number_items[0]['value'];
  }

  $query = db_select('field_data_field_boa_plate', 'f');
  $query
    ->fields('f', array('entity_id', 'field_boa_plate_value'))
    ->condition('f.field_boa_plate_value', $plate_number, '>')
    ->orderBy('f.field_boa_plate_value', 'ASC')
    ->range(0, 1);
  $result = $query->execute();
  $row = $result->fetch();

  if (empty($row)) {
    dpm('empty');
    return $node->nid;
  }

  return $row->entity_id;
}

/**
 * Get entity_id with maximum plate number.
 */
function nas_panes_boa_max() {
  $query = db_select('field_data_field_boa_plate', 'f');
  $query
    ->fields('f', array('entity_id'))
    ->orderBy('f.field_boa_plate_value', 'DESC')
    ->range(0, 1);
  return $query->execute()->fetchField();
}

/**
 * Get entity_id with minimum plate number.
 */
function nas_panes_boa_min() {
  $query = db_select('field_data_field_boa_plate', 'f');
  $query
    ->fields('f', array('entity_id'))
    ->orderBy('f.field_boa_plate_value', 'ASC')
    ->range(0, 1);
  return $query->execute()->fetchField();
}

/**
 * Get the Previous BOA node.
 */
function nas_panes_boa_previous($node) {
  if ($node->nid == nas_panes_boa_min()) {
    return nas_panes_boa_max();
  }

  $plate_number_items = field_get_items('node', $node, 'field_boa_plate');
  $plate_number = 0;
  if (!empty($plate_number_items)) {
    $plate_number = $plate_number_items[0]['value'];
  }

  $query = db_select('field_data_field_boa_plate', 'f');
  $query
    ->fields('f', array('entity_id', 'field_boa_plate_value'))
    ->condition('f.field_boa_plate_value', $plate_number, '<')
    ->orderBy('f.field_boa_plate_value', 'DESC')
    ->range(0, 1);
  $result = $query->execute();
  $row = $result->fetch();

  if (empty($row)) {
    return $node->nid;
  }

  return $row->entity_id;
}
