<?php

/**
 * @file
 * Install, update and uninstall functions for the NetX module.
 */

/**
 * Implements hook_uninstall().
 */
function netx_uninstall() {
  // Remove variables.
  $vars = db_delete('variable');
  $vars = $vars->condition('name', 'netx_%', 'LIKE');
  $vars->execute();
}

/**
 * Set NetX Platform version.
 */
function netx_update_7000() {
  variable_set('netx_authentication_type', NETX_AUTHENTICATION_TYPE_OLD);
}
