<?php

/**
 * @file
 */

/**
* Implementation of hook_menu().
*/
function nas_bird_export_menu() {
  $items = array();

  $items['export/node-list/%'] = array(
    'title' => t('Export nids of the given content type'),
    'page callback' => 'nas_node_list_callback',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
   );
  $items['export/node/%'] = array(
    'title' => t('Load node object as json of the given nid'),
    'page callback' => 'nas_node_nid_callback',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
   );

   return $items;
}

/**
 * function nas_node_list_callback()
 *
 * @return json with nids list of the given content type.
 *
 */
function nas_node_list_callback($content_type) {
  $result = db_query("SELECT nid FROM node WHERE type = '%s'", $content_type);
  $nids = array();
  while ($obj = db_fetch_object($result)) {
    $nids[] = $obj->nid;
  }

  print json_encode($nids);
}

/**
 * function nas_node_nid_callback()
 *
 * @return json of the given node by nid.
 *
 */
function nas_node_nid_callback($nid) {
  $node = node_load($nid);

  print json_encode(array($node));
}
