<?php
/**
 * @file
 * nas_i18n_file routines.
 */

/**
 * Implements hook_entity_info().
 */
function nas_i18n_file_entity_info() {
  $info = array();

  if (module_exists('file_entity')) {
    $info['file'] = array(
      'translation' => array(
        // We need this translation handler to get fields translatable.
        'dummy_translation' => array(
          'dummy' => TRUE,
        ),
      ),
      'language callback' => 'nas_i18n_file_entity_language_callback',
    );
  }

  return $info;
}

/**
 * Return current site language instead of entity language.
 *
 * @param string $entity_type
 *  Type of inspected entity, is not in use.
 * @param mixed $entity
 *  Inspected entity, is not in use.
 *
 * @return string
 *  Language code.
 */
function nas_i18n_file_entity_language_callback($entity_type, $entity) {
  global $language;
  $langcode = $language->language;
  $default_language = language_default();
  $default_langcode = $default_language->language;

  return $langcode == $default_langcode ? LANGUAGE_NONE : $langcode;
}
