<?php
/**
 * @file
 * nas_conservation_news_feature.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function nas_conservation_news_feature_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Climate Change',
    'description' => '',
    'format' => 'map',
    'weight' => 0,
    'uuid' => '141ec25d-c35d-4d61-a656-a1e3b10c2e29',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'conservation_news_tracker',
    'field_conservation_news_icon' => array(
      'und' => array(
        0 => array(
          'fid' => 'ef22f0a4-74f8-4483-b335-cf8b0f72cce1',
          'filename' => 'conservation_news_icon_climate-change.gif',
          'uri' => 'public://conservation_news_icon_climate-change.gif',
          'filemime' => 'image/gif',
          'filesize' => 2016,
          'status' => 1,
          'timestamp' => 1496833577,
          'type' => 'image',
          'uuid' => 'ef22f0a4-74f8-4483-b335-cf8b0f72cce1',
          'field_file_image_alt_text' => array(),
          'field_file_image_title_text' => array(),
          'field_file_caption' => array(),
          'field_file_credit' => array(),
          'metadata' => array(
            'height' => 37,
            'width' => 45,
          ),
          'alt' => NULL,
          'title' => NULL,
          'width' => 45,
          'height' => 37,
          'user_uuid' => '4bf1b159-87cc-4b07-b2fe-bff20b35eed2',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Wildlife',
    'description' => '',
    'format' => 'map',
    'weight' => 0,
    'uuid' => '22545e7d-4167-4123-8dbb-60e9af3a4217',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'conservation_news_tracker',
    'field_conservation_news_icon' => array(
      'und' => array(
        0 => array(
          'fid' => 'c30a2722-dd91-459f-a22d-de1abd3a3224',
          'filename' => 'conservation_news_icon_wildlife.gif',
          'uri' => 'public://conservation_news_icon_wildlife.gif',
          'filemime' => 'image/gif',
          'filesize' => 1737,
          'status' => 1,
          'timestamp' => 1496836775,
          'type' => 'image',
          'uuid' => 'c30a2722-dd91-459f-a22d-de1abd3a3224',
          'field_file_image_alt_text' => array(),
          'field_file_image_title_text' => array(),
          'field_file_caption' => array(),
          'field_file_credit' => array(),
          'metadata' => array(
            'height' => 41,
            'width' => 43,
          ),
          'alt' => NULL,
          'title' => NULL,
          'width' => 43,
          'height' => 41,
          'user_uuid' => '4bf1b159-87cc-4b07-b2fe-bff20b35eed2',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Energy',
    'description' => '',
    'format' => 'map',
    'weight' => 0,
    'uuid' => '8049b55a-ad80-4326-848e-a3155b2f8048',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'conservation_news_tracker',
    'field_conservation_news_icon' => array(
      'und' => array(
        0 => array(
          'fid' => '3f2b0b6b-a125-4d11-841f-5bef2dcd54c3',
          'filename' => 'conservation_news_icon_energy.gif',
          'uri' => 'public://conservation_news_icon_energy.gif',
          'filemime' => 'image/gif',
          'filesize' => 1722,
          'status' => 1,
          'timestamp' => 1496834420,
          'type' => 'image',
          'uuid' => '3f2b0b6b-a125-4d11-841f-5bef2dcd54c3',
          'field_file_image_alt_text' => array(),
          'field_file_image_title_text' => array(),
          'field_file_caption' => array(),
          'field_file_credit' => array(),
          'metadata' => array(
            'height' => 42,
            'width' => 31,
          ),
          'alt' => NULL,
          'title' => NULL,
          'width' => 31,
          'height' => 42,
          'user_uuid' => '4bf1b159-87cc-4b07-b2fe-bff20b35eed2',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Habitat',
    'description' => '',
    'format' => 'map',
    'weight' => 0,
    'uuid' => '834ae96e-2be8-4116-977e-93d7e0d4cf1e',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'conservation_news_tracker',
    'field_conservation_news_icon' => array(
      'und' => array(
        0 => array(
          'fid' => 'c1b2fc5f-1294-495d-bb04-5d8d59025bb0',
          'filename' => 'conservation_news_icon_habitat.gif',
          'uri' => 'public://conservation_news_icon_habitat.gif',
          'filemime' => 'image/gif',
          'filesize' => 1943,
          'status' => 1,
          'timestamp' => 1496836778,
          'type' => 'image',
          'uuid' => 'c1b2fc5f-1294-495d-bb04-5d8d59025bb0',
          'field_file_image_alt_text' => array(),
          'field_file_image_title_text' => array(),
          'field_file_caption' => array(),
          'field_file_credit' => array(),
          'metadata' => array(
            'height' => 42,
            'width' => 41,
          ),
          'alt' => NULL,
          'title' => NULL,
          'width' => 41,
          'height' => 42,
          'user_uuid' => '4bf1b159-87cc-4b07-b2fe-bff20b35eed2',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Water',
    'description' => '',
    'format' => 'map',
    'weight' => 0,
    'uuid' => 'b576be15-d35d-4f95-a5dc-afaa44f1e13c',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'conservation_news_tracker',
    'field_conservation_news_icon' => array(
      'und' => array(
        0 => array(
          'fid' => '99db8883-7d10-406e-8fe9-359c33b0fbc9',
          'filename' => 'conservation_news_icon_water.gif',
          'uri' => 'public://conservation_news_icon_water.gif',
          'filemime' => 'image/gif',
          'filesize' => 1874,
          'status' => 1,
          'timestamp' => 1496836435,
          'type' => 'image',
          'uuid' => '99db8883-7d10-406e-8fe9-359c33b0fbc9',
          'field_file_image_alt_text' => array(),
          'field_file_image_title_text' => array(),
          'field_file_caption' => array(),
          'field_file_credit' => array(),
          'metadata' => array(
            'height' => 42,
            'width' => 42,
          ),
          'alt' => NULL,
          'title' => NULL,
          'width' => 42,
          'height' => 42,
          'user_uuid' => '4bf1b159-87cc-4b07-b2fe-bff20b35eed2',
        ),
      ),
    ),
  );
  $terms[] = array(
    'name' => 'Air',
    'description' => '',
    'format' => 'map',
    'weight' => 0,
    'uuid' => 'd7aa8fa1-d837-4c4e-8d5f-18efe5adef66',
    'language' => 'und',
    'i18n_tsid' => 0,
    'vocabulary_machine_name' => 'conservation_news_tracker',
    'field_conservation_news_icon' => array(
      'und' => array(
        0 => array(
          'fid' => '0c2e248c-ebec-47b7-be5a-936c38cf855e',
          'filename' => 'conservation_news_icon_air.gif',
          'uri' => 'public://conservation_news_icon_air.gif',
          'filemime' => 'image/gif',
          'filesize' => 1930,
          'status' => 1,
          'timestamp' => 1496830028,
          'type' => 'image',
          'uuid' => '0c2e248c-ebec-47b7-be5a-936c38cf855e',
          'field_file_image_alt_text' => array(),
          'field_file_image_title_text' => array(),
          'field_file_caption' => array(),
          'field_file_credit' => array(),
          'metadata' => array(
            'height' => 42,
            'width' => 40,
          ),
          'alt' => NULL,
          'title' => NULL,
          'width' => 40,
          'height' => 42,
          'user_uuid' => '4bf1b159-87cc-4b07-b2fe-bff20b35eed2',
        ),
      ),
    ),
  );
  return $terms;
}
