<?php
/**
 * @file
 * Code for the NAS Conservation Tracker feature.
 */

include_once 'nas_conservation_tracker.features.inc';

/**
 * Implements hook_init().
 */
function nas_conservation_tracker_init() {
  //drupal_add_library('leaflet', 'leaflet', TRUE);
  //libraries_load('leaflet');
}

function nas_conservation_tracker_libraries_info_alter(&$libraries) {
  //print_r($libraries); exit;
  //$libraries['leaflet']['version arguments']['pattern'] = '/version="(\d+(\.\d+)+)"/';
  $libraries['leaflet']['version arguments']['lines'] = 137000;
  $libraries['leaflet']['version arguments']['cols'] = 150000;

  //$libraries['d3']['files']['js']['data'] = 'd3.min.js';

}

/**
 * Implements hook_ctools_plugin_directory().
 */
function nas_conservation_tracker_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_libraries_info().
 */
function nas_conservation_tracker_libraries_info() {
  $libraries = array();

  // Drupal ext adds behaviors and d3 global object.
  $libraries['d3.ct_linegraph'] = array(
    'name' => 'CT Line Graph',
    'vendor url' => 'http://audubon.org',
    'files' => array(
      'js' => array(
        'ct_linegraph.js',
      ),
    ),
    'path' => 'js',
    'library path' => drupal_get_path('module', 'nas_conservation_tracker'),
    'dependencies' => array('d3', 'd3.extend', 'd3.tooltip', 'd3.drupal'),
    'version' => '1',
  );
  return $libraries;
}

/**
 * Implements hook_libraries_info_file_paths().
 */
function nas_conservation_tracker_libraries_info_file_paths() {
  // Get all library directories.
  $libraries = libraries_get_libraries();

  $paths = array();
  // Output an array of paths to check for.
  foreach ($libraries as $path) {
    $paths[] = $path;
  }

  // Add to the search directories for libraries.
  $paths[] = drupal_get_path('module', 'nas_conservation_tracker') . '/libraries/d3.ct_linegraph';

  return $paths;
}


/**
 * Implements hook_theme().
 */
function nas_conservation_tracker_theme() {
  $theme = array(
    'ct_scorecard_header' => array(
      'variables' => array(
        'name' => NULL,
        'image' => NULL,
        'application' => NULL,
        'description' => NULL,
      ),
      'template' => 'templates/ct-scorecard-header',
    ),
    'ct_scorecard_tabs' => array(
      'variables' => array(
        'menu_tree' => NULL,
        'tabs' => NULL,
      ),
      'template' => 'templates/ct-scorecard-tabs',
    ),
    'ct_scorecard_tabs' => array(
      'variables' => array(
        'menu_tree' => NULL,
        'tabs' => NULL,
      ),
      'template' => 'templates/ct-scorecard-tabs',
    ),
    'ct_scorecard_overview' => array(
      'variables' => array(
        'title' => NULL,
        'description' => NULL,
        'media' => NULL,
      ),
      'template' => 'templates/ct-scorecard-overview',
    ),
    'ct_scorecard_main' => array(
      'variables' => array(
        'map' => NULL,
      ),
      'template' => 'templates/ct-scorecard-main',
    ),
    'ct_scorecard_carousel' => array(
      'variables' => array(
        'title' => NULL,
        'items' => NULL,
      ),
      'template' => 'templates/ct-scorecard-carousel',
    ),
  );
  return $theme;
}
