<?php
/**
 * @file
 * Update hooks.
 */

/**
 * Create scorecard node(s).
 */
function nas_conservation_tracker_update_7001() {
  $data = nas_conservation_tracker_get_json('scorecard-123');
  $node = new StdClass();
  $node->type = 'ct_scorecard';
  $node->status = 1;
  $node->language = LANGUAGE_NONE;
  $node->title = $data['name'];
  $node->field_scorecard_id[LANGUAGE_NONE][0]['value'] = $data['id'];
  node_object_prepare($node);
  $node = node_submit($node);
  node_save($node);
}