<?php
/**
 * @file
 * Code for the NAS Conservation Tracker feature.
 */

include_once 'nas_conservation_tracker.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function nas_conservation_tracker_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_theme().
 */
function nas_conservation_tracker_theme() {
  $theme = array(
    'ct_scorecard_header' => array(
      'variables' => array(
        'name' => NULL,
        'image' => NULL,
        'application' => NULL,
        'description' => NULL,
      ),
      'template' => 'templates/ct-scorecard-header',
    ),
    'ct_scorecard_tabs' => array(
      'variables' => array(
        'menu_tree' => NULL,
        'tabs' => NULL,
      ),
      'template' => 'templates/ct-scorecard-tabs',
    ),
    'ct_scorecard_tabs' => array(
      'variables' => array(
        'menu_tree' => NULL,
        'tabs' => NULL,
      ),
      'template' => 'templates/ct-scorecard-tabs',
    ),
    'ct_scorecard_overview' => array(
      'variables' => array(
        'title' => NULL,
        'description' => NULL,
        'media' => NULL,
      ),
      'template' => 'templates/ct-scorecard-overview',
    ),
    'ct_scorecard_main' => array(
      'variables' => array(

      ),
      'template' => 'templates/ct-scorecard-main',
    ),
    'ct_scorecard_carousel' => array(
      'variables' => array(
        'title' => NULL,
        'items' => NULL,
      ),
      'template' => 'templates/ct-scorecard-carousel',
    ),
  );
  return $theme;
}
