<?php

/**
 * @file
 * For hook_update_X functions.
 */

function nas_sla_install() {
  features_revert_module('nas_news_page_feature');
}

function nas_sla_update_7101() {
  features_revert_module('nas_static_page_feature');
  features_revert_module('nas_slideshow_feature');
}
/**
 * Revert features.
 */
function nas_master_update_7102() {
  features_revert_module('nas_static_page_feature');
  features_revert_module('nas_slideshow_feature');
}
