<?php
/**
 * @file
 * Code for the NAS Mobapp Endpoint feature.
 */

include_once 'nas_mobapp_endpoint.features.inc';

/**
 * Implements hook_menu().
 */
function nas_mobapp_endpoint_menu() {
  $items = array();

  $items['get_endpoint'] = array(
    'title' => 'GET ednpoint',
    'description' => 'Get endpoint',
    'access callback' => TRUE,
    'page callback' => 'nas_mobapp_endpoint_get_endpoint',
    'delivery callback' => 'drupal_json_output',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Endpoint callback.
 */
function nas_mobapp_endpoint_get_endpoint() {
  // Prevent the page from being cached.
  drupal_page_is_cacheable(FALSE);
  $type = (!empty($_GET['type'])) ? $_GET['type'] : '';
  $amount = (!empty($_GET['amount'])) ? $_GET['amount'] : '';
  $language = (!empty($_SERVER['HTTP_ACCEPT_LANGUAGE'])) ? $_SERVER['HTTP_ACCEPT_LANGUAGE'] : '';
  $types = array('article' => 'block', 'action' => 'block_1');
  $lang = (!empty($language) && $language == 'es') ? 'es' : LANGUAGE_NONE;
  $amount = intval($amount);
  if (!empty($types[$type]) && $amount > 0) {
    $view_results = views_get_view_result('mobile_app', $types[$type], $lang);
    $counted = count($view_results);
    if ($counted > $amount) {
      $view_results = array_slice($view_results, 0, $amount);
    }
    foreach ($view_results as &$view_result) {
      $item = array();
      global $base_url;
      $item['title'] = trim($view_result->node_title);
      $item['summary'] = !empty($view_result->field_body[0]['rendered']['#markup']) ? strip_tags($view_result->field_body[0]['rendered']['#markup']) : '';
      $item['position'] = $view_result->nodequeue_nodes_node_position;
      $uri = '';
      if ($type == 'article') {
        $item['url'] = $base_url . '/node/' . $view_result->nid;
        $item['slug'] = !empty($view_result->taxonomy_term_data_node_name) ? $view_result->taxonomy_term_data_node_name : '';
        if (!empty($view_result->field_field_hero_image_1[0]['raw']['file']->uri)) {
          $uri = $view_result->field_field_hero_image_1[0]['raw']['file']->uri;
        }
      }
      else {
        $item['url'] = !empty($view_result->field_field_link[0]['raw']['url']) ? $view_result->field_field_link[0]['raw']['url'] : '';
        $item['slug'] = !empty($view_result->field_field_slug[0]['rendered']['#markup']) ? $view_result->field_field_slug[0]['rendered']['#markup'] : '';
        if (!empty($view_result->field_field_image[0]['raw']['uri'])) {
          $uri = $view_result->field_field_image[0]['raw']['uri'];
        }
      }

      if (!empty($uri)) {
        $uri = nas_alters_local_image_uri($uri);
        $item['image'] = image_style_url('mobapp', $uri);
      }
      $view_result = $item;
    }
    return $view_results;
  }
  return NULL;
}
