---

jetty_solr_dependencies:
  - 'openjdk-7-jdk'
jetty_solr_port: 8983
jetty_solr_version: 4.7.2
jetty_solr_module: 'search_api_solr'
jetty_solr_module_version: 'search_api_solr-7.x-1.6'
jetty_solr_module_config_path: 'solr-conf/4.x'
jetty_solr_module_force_download: true
# Here is an example for apachesolr module integration
# jetty_solr_module: 'apachesolr'
# jetty_solr_module_version: 'apachesolr'
# jetty_solr_module_config_path: 'solr-conf/solr-4.x'
# jetty_solr_module_force_download: false
jetty_solr_cores:
  default:
    name: default
    config_version: 4.x
    module: search_api_solr
  build:
    name: build
    config_version: 4.x
    module: search_api_solr
  demo:
    name: demo
    config_version: 4.x
    module: search_api_solr
jetty_solr_extra_configs:
  - /var/www/docroot/sites/all/modules/custom/nas_search/solr-conf/schema_extra_fields.xml
  - /var/www/docroot/sites/all/modules/custom/nas_search/solr-conf/schema_extra_types.xml
