<?php

/**
 * @file
 * Empty file. All code to be plased to nas_master.install.
 */


/**
 * Implements hook_form_alter().
 */
function nas_master_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form['#id'] == 'views-exposed-form-nas-bird-guide-nas-bird-guide-fav-birds') {
    $form['submit']['#value'] = '<span class="hide-for-medium hide-for-large hide-for-xlarge"><i class="icon-magnifier"></i></span><span class="hide-for-tiny hide-for-small">' . $form['submit']['#value'] . '</span>';
    $form['submit']['#attributes']['class'][] = 'bird-guide-search-submit';
    $form['submit']['#attributes']['class'][] = 'button';
    $form['submit']['#attributes']['class'][] = 'pea-green';
    $form['field_bird_call_type_tid']['#options']['All'] = t('Type of Bird');
    $form['field_bird_family_tid']['#options']['All'] = t('Taxonomic Family');
    $form['field_bird_region_tid']['#options']['All'] = t('Region');
  }
}

/**
 * Implements hook_views_ajax_data_alter().
 */
function nas_master_views_ajax_data_alter(&$commands, $view) {
  if ($view->current_display == 'nas_bird_guide_fav_birds') {
    $commands[] = ajax_command_replace('.bird-card-grid .section-header h2', '<h2 class="thin">' . t('Matching Birds') . '</h2>');
  }
}
