<?php
/**
 * @file
 * Drupal needs this blank file.
 */

define('NAS_LIVE_SITE_URL', 'http://www.audubon.org/');

/**
 * Custom function for saving files.
 */
function nas_master_add_existing_file($file_drupal_path, $type, $uid = 1, $status = FILE_STATUS_PERMANENT) {
  $files = file_load_multiple(array(), array('uri' => $file_drupal_path));
  $file = reset($files);

  if (!$file) {
    $file = (object) array(
        'filename' => basename($file_drupal_path),
        'filepath' => $file_drupal_path,
        'filemime' => file_get_mimetype($file_drupal_path),
        'filesize' => filesize($file_drupal_path),
        'uid' => $uid,
        'status' => $status,
        'timestamp' => time(),
        'uri' => $file_drupal_path,
        'type' => $type,
    );
    drupal_write_record('file_managed', $file);
  }
  return $file;
}

/**
 * Implements hook_feeds_presave().
 */
function nas_master_feeds_presave(FeedsSource $source, $entity, $item) {
  if ($entity->feeds_item->id == 'birds_import') {
    // Save speices_image field data to field_bird_photo.
    if (!empty($item['field_speices_image'])) {
      foreach ($item['field_speices_image'] as $key => $value) {
        if (isset($value['fid'])) {
          $remoteDocPath = NAS_LIVE_SITE_URL . str_replace('%2F', '/', rawurlencode($value['filepath']));
          $doc = system_retrieve_file($remoteDocPath, NULL, FALSE, FILE_EXISTS_REPLACE);
          $file = nas_master_add_existing_file($doc, 'image');
          $entity->field_bird_photo[LANGUAGE_NONE][$key]['fid'] = $file->fid;

          // Additionally save Alt and Title if exist
          if (!empty($value['data']['alt']) || (!empty($value['data']['title']))) {
            $file_entity = file_load($file->fid);
            $file_entity->field_file_image_alt_text[LANGUAGE_NONE][0]['value'] = $value['data']['alt'];
            $file_entity->field_file_image_title_text[LANGUAGE_NONE][0]['value'] = $value['data']['title'];
            file_save($file_entity);
          }
        }
      }
    }
    // Save field_rangemaps field data to field_bird_rangemap.
    if (!empty($item['field_rangemaps'])) {
      foreach ($item['field_rangemaps'] as $key => $value) {
        if (isset($value['fid'])) {
          $remoteDocPath = NAS_LIVE_SITE_URL . str_replace('%2F', '/', rawurlencode($value['filepath']));
          $doc = system_retrieve_file($remoteDocPath, NULL, FALSE, FILE_EXISTS_REPLACE);
          $file = nas_master_add_existing_file($doc, 'image');
          $entity->field_bird_rangemap[LANGUAGE_NONE][$key]['fid'] = $file->fid;

          // Additionally save Alt and Title if exist
          if (!empty($value['data']['alt']) || (!empty($value['data']['title']))) {
            $file_entity = file_load($file->fid);
            $file_entity->field_file_image_alt_text[LANGUAGE_NONE][0]['value'] = $value['data']['alt'];
            $file_entity->field_file_image_title_text[LANGUAGE_NONE][0]['value'] = $value['data']['title'];
            file_save($file_entity);
          }
        }
      }
    }
    // Save field_bird_call field data to field_bird_audio.
    if (!empty($item['field_bird_call'])) {
      foreach ($item['field_bird_call'] as $key => $value) {
        if (isset($value['fid'])) {
          $remoteDocPath = NAS_LIVE_SITE_URL . str_replace('%2F', '/', rawurlencode($value['filepath']));
          $doc = system_retrieve_file($remoteDocPath, NULL, FALSE, FILE_EXISTS_REPLACE);
          $file = nas_master_add_existing_file($doc, 'audio');
          $entity->field_bird_audio[LANGUAGE_NONE][$key]['fid'] = $file->fid;

          // Additionally save description if exist to separate field field_audio_description
          if (!empty($value['data']['description'])) {
            $file_entity = file_load($file->fid);
            $file_entity->field_audio_description[LANGUAGE_NONE][0]['value'] = $value['data']['description'];
            file_save($file_entity);
          }
        }
      }
    }
  }
}
