<?php

/**
 * @file
 * i18n_node_load routines.
 */

/**
 * i18n wrapper over standard node_load().
 */
function _i18n_node_load($nid = NULL, $vid = NULL, $reset = FALSE) {
  if (!function_exists('translation_node_get_translations')) {
    return node_load($nid, $vid, $reset);
  }
  global $language;
  $all_translations = translation_node_get_translations($nid);
  if (isset($all_translations[$language->language])) {
    return node_load($all_translations[$language->language]->nid, $vid, $reset);
  }
  if (isset($all_translations[LANGUAGE_NONE])) {
    return node_load($all_translations[LANGUAGE_NONE]->nid, $vid, $reset);
  }
  return node_load($nid, $vid, $reset);
}
