<?php

/**
 * @file
 * Provides wysiwys's plugins.
 */

define('NAS_WYSIWYG_LOGO_WELCOME_TO_ADUBON', 'wordmark-black.png');

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function nas_wysiwyg_wysiwyg_editor_settings_alter() {
  drupal_add_css(drupal_get_path('module', 'nas_wysiwyg') . '/css/nas_wysiwyg.css');
}

/**
 * Implements hook_wysiwyg_include_directory().
 */
function nas_wysiwyg_wysiwyg_include_directory($type) {
  return 'plugins';
}

/**
 * Implements hook_filter_info().
 */
function nas_wysiwyg_filter_info() {
  $filters['nas_wysiwyg_article_aside_filter'] = array(
    'title' => t('Convert NAS article aside Insert tags to markup'),
    'description' => t('This filter will convert [article_aside_insert]...[/article_aside_insert] tags into markup.'),
    'process callback' => 'nas_wysiwyg_article_aside_filter_process',
    'weight' => 2,
  );
  return $filters;
}

/**
 * Implements hook_element_info_alter().
 */
function nas_wysiwyg_element_info_alter(&$types) {
  $types['text_format']['#pre_render'][] = 'nas_wysiwyg_article_aside_pre_render_text_format';
}

/**
 * Preprocess function for entity.
 */
function nas_wysiwyg_preprocess_entity(&$vars) {
  // preprocess_bean__[bundle] doesn't work.
  if ($vars['elements']['#entity_type'] !== 'bean') {
    return;
  }
  $vars['theme_hook_suggestions'][] = 'bean__' . $vars['elements']['#bundle'];
  if ($vars['elements']['#bundle'] == 'wysiwyg_image') {
    $entity = $vars['elements']['#entity'];
    $get_field_wysiwyg_image = field_get_items('bean', $entity, 'field_wysiwyg_image');
    if (!empty($get_field_wysiwyg_image)) {
      $get_field_file_caption = field_view_field('file', $get_field_wysiwyg_image[0]['file'], 'field_file_caption');
      $get_field_file_credit = field_view_field('file', $get_field_wysiwyg_image[0]['file'], 'field_file_credit');
      $vars['figcaption'] = '';
      if (!empty($get_field_file_caption)) {
        $vars['figcaption'] .= $get_field_file_caption[0]['#markup'] .'&nbsp;';
      }
      if (!empty($get_field_file_credit)) {
        $vars['figcaption'] .= $get_field_file_credit[0]['#markup'];
      }
      $vars['figcaption'] = strip_tags($vars['figcaption'], '<a>');
    }
    $get_field_wysiwyg_width_mode = field_get_items('bean', $entity, 'field_wysiwyg_width_mode');
    $vars['width'] = $get_field_wysiwyg_width_mode[0]['value'];
  }
  elseif ($vars['elements']['#bundle'] == 'welcome_to_audubon') {
    $entity = $vars['elements']['#entity'];
    $vars_array_data = get_welcome_to_audubon_array_data($entity);
    $vars['content'] = theme('bean__welcome_to_audobun', $vars_array_data);
  }
}

/**
 * Function to get array data variebles to block welcome_to_adubun.
 */
function get_welcome_to_audubon_array_data(&$entity) {
  global $base_url;
  // Set image to logo block welcome to audobun.
  $path_to_logo = $base_url . '/' . drupal_get_path('module', 'nas_wysiwyg') . '/image/' . NAS_WYSIWYG_LOGO_WELCOME_TO_ADUBON;
  // Get image.
  $block_image = field_get_items('bean', $entity, 'field_welcome_image');
  $image = theme('image', array('path' => url($block_image[0]['value'])));
  // Get summary.
  $get_field_summary = field_get_items('bean', $entity, 'field_summary_welcome_first');
  $summary = $get_field_summary[0]['value'];
  // Get color.
  $color = $color_style = NULL;
  $get_field_color = field_get_items('bean', $entity, 'field_background_welcome_first');
  if (!empty($get_field_color)) {
    $color = $get_field_color[0]['rgb'];
    $color_style = "color:$color";
  }
  // Get link 'Learn more'.
  $get_field_learn_more = field_get_items('bean', $entity, 'field_learn_more_welcome_first');
  if (!empty($get_field_learn_more)) {
    $link_more = l($get_field_learn_more[0]['title'], $get_field_learn_more[0]['url'], array('attributes' => array('style' => $color_style)));
  }
  // Get link in the news.
  $view_results = views_get_view_result('random_news', 'master');
  if (!empty($view_results)) {
    $path_news = $base_url . '/news';
    $link_news = l($view_results[0]->node_title, 'node/' . $view_results[0]->nid, array('attributes' => array('style' => $color_style)));
  }
  // Get link most popular.
  $view_results = views_get_view_result('nas_most_viewed_articles', 'nas_most_viewed_articles');
  if (!empty($view_results)) {
    $path_most_popular = $base_url;
    $link_most_popular = l($view_results[0]->node_title, 'node/' . $view_results[0]->nid, array('attributes' => array('style' => $color_style)));
  }
  return array(
    'image' => $image,
    'path_to_logo' => $path_to_logo,
    'summary' => $summary,
    'link_more' => $link_more,
    'path_news' => $path_news,
    'link_news' => $link_news,
    'path_most_popular' => $path_most_popular,
    'link_most_popular' => $link_most_popular,
    'social_link_fb' => 'https://www.facebook.com/NationalAudubonSociety',
    'social_link_tw' => 'https://twitter.com/audubonsociety',
    'social_link_yotube' => 'https://www.youtube.com/user/NationalAudubon',
    'social_link_pi' => 'https://www.pinterest.com/audubonsociety/',
    'color' => $color,
  );
}

/**
 * Implements hook_theme().
 */
function nas_wysiwyg_theme() {
  return array(
    'nas_article_aside' => array(
      'variables' => array(
        'head' => '',
        'text' => '',
      ),
      'template' => 'nas-article-aside',
      'path' => drupal_get_path('module', 'nas_wysiwyg') . '/theme'
    ),
    'bean__wysiwyg_image' => array(
      'variables' => array(
        'head' => '',
        'text' => '',
      ),
      'template' => 'bean--wysiwyg_image',
      'path' => drupal_get_path('module', 'nas_wysiwyg') . '/theme'
    ),
    'bean__welcome_to_audobun' => array(
      'variables' => array(
        'image' => '',
        'path_to_logo' => '',
        'summary' => '',
        'path_more' => '',
        'link_more' => '',
        'path_news' => '',
        'link_most_popular' => '',
        'path_most_popular' => '',
        'social_link_fb' => '',
        'social_link_tw' => '',
        'social_link_yotube' => '',
        'social_link_pi' => '',
        'color' => '',
      ),
      'template' => 'bean--welcome_to_audobun',
      'path' => drupal_get_path('module', 'nas_wysiwyg') . '/theme'
    ),
  );
}

/**
 * Pre render function for text_format.
 */
function nas_wysiwyg_article_aside_pre_render_text_format($element) {
  // filter_process_format() copies properties to the expanded 'value' child
  // element.
  if (!isset($element['format'])) {
    return $element;
  }

  $field = &$element['value'];
  $tagmap = _nas_wysiwyg_article_aside_generate_tagMap($field['#value']);

  if (isset($tagmap)) {
    drupal_add_js(array('nas_wysiwyg_tagmap' => $tagmap), 'setting');
  }
  return $element;
}

/**
 * Finds all matches and run them through nas_wysiwyg_article_aside_token_to_markup().
 */
function nas_wysiwyg_article_aside_filter_process($text) {
  $text = ' ' . $text . ' ';
  $text = preg_replace_callback("/\[article_aside_insert\].*?\[\/article_aside_insert\]/s", 'nas_wysiwyg_article_aside_token_to_markup', $text);
  return $text;
}

/**
 * Convert tokens to markup.
 */
function nas_wysiwyg_article_aside_token_to_markup($match) {
  preg_match("/\[head\](.*?)\[\/head\]/s", $match[0], $head);
  preg_match("/\[text\](.*?)\[\/text\]/s", $match[0], $text);
  $text = theme('nas_article_aside', array(
    'head' => $head[1],
    'text' => $text[1],
    )
  );
  return $text;
}

/**
 * Tagmap generator function.
 */
function _nas_wysiwyg_article_aside_generate_tagMap($text) {
  static $tagmap = array();
  preg_match_all("/\[article_aside_insert\].*?\[\/article_aside_insert\]/s", $text, $matches, PREG_SET_ORDER);
  foreach ($matches as $match) {
    if (empty($tagmap[$match[0]])) {
      $markup = nas_wysiwyg_article_aside_token_to_markup($match);
      $tagmap[$match[0]] = $markup;
    }
  }
  return $tagmap;
}
