<?php
/**
 * @file
 * Code for the NAS Park feature feature.
 */

include_once 'nas_park_feature.features.inc';

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function nas_park_feature_form_park_node_form_alter(&$form, &$form_state, $form_id) {
  $states = $form['field_state'][LANGUAGE_NONE]['#options'];
  unset($states['_none']);
  foreach ($states as $tid => $title) {
    $term = taxonomy_term_load($tid);
    if($term->field_country_us_ca[LANGUAGE_NONE][0]['value'] != 'us') {
      unset($form['field_state'][LANGUAGE_NONE]['#options'][$tid]);
    }
  }
}

/**
 * Helper function to load images.
 */
function nas_park_feature_get_image($name) {
  $files = file_load_multiple(array(), array('filename' => $name));
  $file = reset($files);
  $image_url = variable_get('nas_park_feature_assets', 'sites/all/themes/custom/nas/img/climate-landing') . '/' . $name;
  if (empty($file)) {
    if (file_exists($image_url)) {
      $file = file_save_data(file_get_contents($image_url), 'public://' . basename($image_url));
      $file->status = 1;
      return $file;
    }
    return FALSE;
  }
  else {
    if (!file_exists($file->uri)) {
      if (file_exists($image_url)) {
        file_put_contents('public://' . basename($image_url), file_get_contents($image_url));
        return $file;
      }
    }
    return $file;
  }
}
