<?php

/**
 * @file
 * Provides actions.
 */

/**
 * Implements hook_action_info().
 */
function nas_i18n_actions_action_info() {
  return array(
    'nas_i18n_actions_create_spanish_translation_action' => array(
      'type' => 'node',
      'label' => t('Create Spanish Translation'),
      'configurable' => FALSE,
      'triggers' => array(
        'node_presave',
        'node_insert',
        'node_update',
      ),
    ),
  );
}

/**
 * Action to create spanish translation.
 */
function nas_i18n_actions_create_spanish_translation_action($node, $context) {
  // We don't clone nodes which already have translation.
  if ($node->language == 'es' || $node->tnid != 0) {
    return;
  }

  $source_node = $node;
  $es_node = clone $source_node;
  $source_node->tnid = $node->nid;
  node_save($source_node);

  unset($es_node->nid);
  unset($es_node->vid);
  unset($es_node->uuid);

  node_object_prepare($es_node);
  $es_node->language = 'es';
  $es_node->status = 0;
  $es_node->tnid = $source_node->nid;
  node_save($es_node);
}
